"""create tracked keywords table

Revision ID: aa8379517dc7
Revises: 54a8ad1dc385
Create Date: 2026-05-28 11:27:20.882492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8379517dc7'
down_revision: Union[str, Sequence[str], None] = '54a8ad1dc385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_index(op.f('ix_tracked_keywords_id'), 'tracked_keywords', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracked_keywords_id'), table_name='tracked_keywords')
    op.drop_table('tracked_keywords')
    # ### end Alembic commands ###
